### ISSUE TITLE
Is it possible for starting item to be at the left/start instead of center?

### ISSUE THREAD

**Issue by unklenima** [yarolegovich/DiscreteScrollView#100]
Currently the first item is shown in the center of recyclerview which is a bit weird for small items. Is there any way to start from left or start of the recyclerview?

**Comment by yarolegovich** [comment]
What you probably need is a [SnapHelper](https://blog.mindorks.com/using-snaphelper-in-recyclerview-fc616b6833e8).

**Comment by unklenima** [comment]
SnapHelper will cause the recycler to auto-scroll to the end.

**Comment by unklenima** [comment]
any other ideas?

**Comment by yarolegovich** [comment]
Sorry then, I don't know any alternatives and don't plan to add this feature to the library.
