### ISSUE TITLE
Crash when updating the adapters async

### ISSUE THREAD

**Issue by bernaferrari** [yarolegovich/DiscreteScrollView#102]
If you add this:

       Handler handler = new Handler();
        handler.postDelayed(new Runnable() {
            public void run() {
                data.clear();
                infiniteAdapter = InfiniteScrollAdapter.wrap(new ShopAdapter(data));
                itemPicker.setAdapter(infiniteAdapter);
            }
        }, 1000);

below this line: https://github.com/yarolegovich/DiscreteScrollView/blob/7573f8691c9408706decca7f7d29934799db4b24/sample/src/main/java/com/yarolegovich/discretescrollview/sample/shop/ShopActivity.java#L54

It will crash. I'm having the same bug with Firebase, I want to update the items/adapter async, but when rotating the screen it crashes. I believe it is the same root of problem.

If I instead do a 

                data.clear();
                infiniteAdapter.notifyDataSetChanged();
I get the same problem. How do I update the adapter items?

**Comment by yarolegovich** [comment]
Are you sure it crashes because of the library, but not because you are trying to perform operation on an already destroyed activity?

**Comment by bernaferrari** [comment]
Yeah.. If you try the sample I just sent you, without rotating or anything, just executing, it will crash..

**Comment by yarolegovich** [comment]
Ok, I'll look into it on coming weekends.

**Comment by yarolegovich** [comment]
The exception is unrelated to the library. If I modify `onCurrentItemChanged` so that it handles the case with an empty dataset and `shop.getData()` so that it returns a modifiable collection, everything works just fine.

**Comment by bernaferrari** [comment]
Forget everything I said. I tested exhaustively today, and was impressed how it would work in your project, and wouldn't work on my. I even tried to update some of your code to Kotlin, thinking there was something unforeseen, but everything worked fine. 
So I updated the Support Library version on your project, and bang! Same problem as I was having. I just zipped everything. All you have to do is open the app (it will already open on the ShopActivity), and rotate your device. Crash!

Github limits to 10mb, so I uploaded here: https://we.tl/xMjV2EAupW
In case it expires or anything, just warn me.

**Comment by yarolegovich** [comment]
@bernaferrari I really appreciate your effort, thanks for helping with the issue.
Try upgrading to `1.4.7`. The issue should not appear there.
I explained what was causing the issue [here](https://github.com/yarolegovich/DiscreteScrollView/commit/5dd10a14730921bb89a254cdc307c128c10b2a47#diff-bc32104c18fa934b5358f280282abf06R129).

**Comment by bernaferrari** [comment]
Perfect, thanks!!
