### ISSUE TITLE
How to install this library?

### ISSUE THREAD

**Issue by kc980602** [yarolegovich/DiscreteScrollView#104]
![image](https://user-images.githubusercontent.com/29748339/38422715-556ccc10-39de-11e8-9c4d-847d086e14a2.png)
Hi, I am trying to use your library, but I cannot install it.
Do this library support SDK 26?
Thanks!

**Comment by kc980602** [comment]
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    buildToolsVersion "26.0.2"
    defaultConfig {
        applicationId "com."
        minSdkVersion 21
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'com.android.support:support-v4:27.1.0'
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })

    testCompile 'junit:junit:4.12'
    implementation 'com.android.support:appcompat-v7:27.1.0'
    implementation 'com.android.support:cardview-v7:27.1.0'
    implementation 'com.android.support:recyclerview-v7:27.1.0'
    implementation 'com.android.support:support-vector-drawable:27.1.0'
    implementation 'com.android.support:design:27.1.0'

    // library
    implementation 'com.yarolegovich:discrete-scrollview:1.4.7'

```
After I can to this the Gradle sync success, but another problem came out.

```
Error:Execution failed for task ':app:transformClassesWithInstantRunForDebug'.
> Unexpected inputs: ImmutableJarInput{name=com.android.support:transition:26.1.0, file=...\app\build\intermediates\transforms\profilers-transform\debug\6.jar, contentTypes=CLASSES, scopes=EXTERNAL_LIBRARIES, status=REMOVED}
```

**Comment by yarolegovich** [comment]
Glad you figured this out.

**Comment by azizbekian** [comment]
@yarolegovich what proguard rules to apply?

**Comment by kc980602** [comment]
`apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    buildToolsVersion '27.0.3'
    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'com.android.support:support-v4:27.1.0'
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })

    testCompile 'junit:junit:4.12'
    **implementation 'com.android.support:appcompat-v7:27.1.0'
    implementation 'com.android.support:cardview-v7:27.1.0'
    implementation 'com.android.support:recyclerview-v7:27.1.0'**
    implementation 'com.android.support:support-vector-drawable:27.1.0'
    **implementation 'com.android.support:design:27.1.0'**
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'`
