### ISSUE TITLE
min scale not being reached in the transformer 

### ISSUE THREAD

**Issue by TonyHaddad91** [yarolegovich/DiscreteScrollView#107]
Hey,
Thanks for the awesome library 
I have one issue with the item transformer 
in this method 
`    void transformItem(View item, float position); 
`
the position range is [-1,1]
and in case of 1 or -1  closenessToCenter will be 0 
but as I'm debugging I found that its not reaching 1 or -1 
max value was 0.87f

Any help regarding this ?

**Comment by yarolegovich** [comment]
re #194
