### ISSUE TITLE
Unable to implement onClick 

### ISSUE THREAD

**Issue by surbhitrao** [yarolegovich/DiscreteScrollView#116]
Can someone who has implemented onClick listener help me out.

**Comment by jjhesk** [comment]
this is triggered by another call.

**Comment by yarolegovich** [comment]
Just implement it as if you're working with RecyclerView... [Sample](https://github.com/yarolegovich/DiscreteScrollView/blob/master/sample/src/main/java/com/yarolegovich/discretescrollview/sample/weather/ForecastAdapter.java#L62).
