### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Invalid item position 20(20). Item count:20

### ISSUE THREAD

**Issue by sevar83** [yarolegovich/DiscreteScrollView#12]
I've got the following exception:

```
java.lang.IndexOutOfBoundsException: Invalid item position 20(20). Item count:20
at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5466)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
       at com.yarolegovich.discretescrollview.DiscreteScrollLayoutManager.layoutView(DiscreteScrollLayoutManager.java:160)
       at com.yarolegovich.discretescrollview.DiscreteScrollLayoutManager.fill(DiscreteScrollLayoutManager.java:133)
       at com.yarolegovich.discretescrollview.DiscreteScrollLayoutManager.onLayoutChildren(DiscreteScrollLayoutManager.java:93)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
...
```

Repro:

1. Add N items
2. Remove N items - in DiscreteScrollLayoutManager.onItemsRemoved() `currentPosition` becomes 0 but I think it is more correct to become `-1` (NO_POSITION) as an index range of an empty adapter is also empty. So `currentPosition` is better to be reverted to the initial NO_POSITION.
3. Add some 20 items - in `DiscreteScrollLayoutManager.onItemsAdded()` `currentPosition` becomes 0 + 20 = 20 but it should be 19.

```
public void onItemsRemoved(RecyclerView recyclerView, int positionStart, int itemCount) {
        if (getItemCount() == 0) {
            currentPosition = NO_POSITION;
        } else if (currentPosition >= positionStart) {

            // What about this correction?
            // currentPosition = Math.max(0, currentPosition - itemCount);
            currentPosition = Math.max(NO_POSITION, currentPosition - itemCount);
        }
    }
```

**Comment by yarolegovich** [comment]
Thanks for the issue and your thoughts on it. Maybe you are right. The reason I don't set `currentPosition` to -1 is that I thought `onLayoutChildren` will be called right after it and the condition will be executed:
```java
if (state.getItemCount() == 0) {
    removeAndRecycleAllViews(recycler);
    currentPosition = pendingPosition = NO_POSITION;
    scrolled = pendingScroll = 0;
    return;
}
```
Will test your case and try to fix it asap.

**Comment by yarolegovich** [comment]
Do you call `notifyItemRangeInserted`/`notifyItemRangeRemoved` or `notifyDataSetChanged`?

**Comment by sevar83** [comment]
Yes, the code is working stable with the default RV.

**Comment by yarolegovich** [comment]
Can you please post the code required to reproduce the crash, all my attempts are unsuccessful.

**Comment by sevar83** [comment]
I do the changes via DiffUtil. I suppose everything happens in one layout cycle so `onLayoutChildren` is called after the calls to layout manager's `onItemsRemoved` and `onItemsAdded`. You shouldn't rely on `onLayoutChildren` to do a clean up work. I think you just need to make sure `onItemsRemoved`, `onItemsAdded` are reversible. I mean adding item(s) and then removing them should leave the layout manager in the original state without need to reset it in onLayoutChildren(). If `currentPosition` is initially `NO_POSITION` then it should be reverted to `NO_POSITION` after the removal. It should NOT become 0 when the list is empty as 0 is out of bounds.

My Adapter (kotlin) calls :
```
DiffUtil.calculateDiff(DiffCallback(newItems, oldItems), true)
           .dispatchUpdatesTo(ForcePayloadCallback(this))
```

```
class ForcePayloadCallback(
        val adapter: RecyclerView.Adapter<RecyclerView.ViewHolder>
) : ListUpdateCallback {

    override fun onInserted(position: Int, count: Int) {
        adapter.notifyItemRangeInserted(position, count)
    }

    override fun onRemoved(position: Int, count: Int) {
        adapter.notifyItemRangeRemoved(position, count)
    }

    override fun onMoved(fromPosition: Int, toPosition: Int) {
        adapter.notifyItemMoved(fromPosition, toPosition)
    }

    override fun onChanged(position: Int, count: Int, payload: Any?) {
        adapter.notifyItemRangeChanged(position, count, "forcePartialBind")
    }
}
```

Please just try replacing `Math.max(0` with `Math.max(NO_POSITION` in the layout manager.

**Comment by yarolegovich** [comment]
Look, here is `onItemsRemoved`:
```java
if (getItemCount() == 0) {
    currentPosition = NO_POSITION;
} else if (currentPosition >= positionStart) {
    currentPosition = Math.max(0, currentPosition - itemCount);
}
```
`currentPosition` is set to `NO_POSITION` if `adapter.getItemCount()` returns 0, so the problem is somewhere else.

**Comment by yarolegovich** [comment]
I've manage to reproduce the issue. Working on it.

**Comment by sevar83** [comment]
The problem is in the second branch:
`currentPosition = Math.max(0, currentPosition - itemCount);`

Suppose I have 20 items inserted. 
`currentPosition` is 19. That's correct.
Then I remove 20 of them:
`currentPosition = Math.max(0, 19-20)`. Becomes 0. That's incorrect.

**Comment by yarolegovich** [comment]
```java
currentPosition = Math.max(NO_POSITION, currentPosition - itemCount);
```
Will break other cases. Suppose you have 10 items, `currentPosition == 3` and 7 items are removed, then`Math.max(NO_POSITION, 3 - 7)` will return `NO_POSITION`, but it should return 0.
I better add a check at the end of `onItemsAdded`, like:
```java
currentPosition = Math.min(currentPosition, getItemCount() - 1);
```

**Comment by yarolegovich** [comment]
Use the version `1.1.2` and you won't get the exception. Thanks again for reporting it.

**Comment by sevar83** [comment]
It's working. Thanks for the quick response.
