### ISSUE TITLE
How to stop Snapping?

### ISSUE THREAD

**Issue by AhmedDroid** [yarolegovich/DiscreteScrollView#122]
I'm trying to make the scroll smooth to multiple positions, but the snap helper is making the scroll animation laggy, any idea how to turn it off?

**Comment by yarolegovich** [comment]
This library has nothing to do with SnapHelper.

**Comment by thangmam** [comment]
hello, is it possible to change the center snapping to **START** or **END** ?

**Comment by yarolegovich** [comment]
Not enough details.
