### ISSUE TITLE
Vertical scroll view

### ISSUE THREAD

**Issue by johnbird7** [yarolegovich/DiscreteScrollView#128]
Hey there,
I'm using firebase to get my data. When I use recyclerview I'm able to fetch data but when I replace it with descretescrollview data isn't fetched. I really like the vertical scroll view. 

Here's what  I did 

1) replace recyclerview with descretescrollview
2)set orientation to vertical
3)removed layout manager 

Anything else to be done? How do I implement the overlay effect?

Thank you

**Comment by yarolegovich** [comment]
The overlay effect is provided in the sample.
Can't tell why data wasn't fetched, probably you were using a wrong callback to trigger loading. See:
https://github.com/yarolegovich/DiscreteScrollView#callbacks
