### ISSUE TITLE
Fast Scroll

### ISSUE THREAD

**Issue by iordachiv** [yarolegovich/DiscreteScrollView#13]
Hello.
I want to ask you if is possible to implement fast scroll over items? when user swipe to change position not only pre/next slide. Can you please guide me how is possible to implement for your ScrollView.

**Comment by yarolegovich** [comment]
Hi.
Fast scroll initiated by the user is not supported and it will be rather hard to implement it. Take a look at `smoothScrollToPosition`, maybe you will be able to somehow combine it with fling detection in onTouchListener.
