### ISSUE TITLE
No Values outside -1 < x < 1 sent to Transformers.

### ISSUE THREAD

**Issue by joeShuff** [yarolegovich/DiscreteScrollView#131]
When creating a Transformer, the `transformItem()` method never gets passed a `position` less than -1 or greater than 1. However, I am wanting to create a circular effect with this library.

For example, if I have 3 items on the screen, and 1 item off screen either side. When swiping, I want the items that are off the screen to come from a lower position than the one currently on the edge of the screen, using the position in the transformer.

I noticed in the `DiscreteScrollLayoutTransformer` that the `getCenterRelativePositionOf()` method returns a min of -1 and a max of 1, and it is being purposely limited, is there reasoning behind this?

![ezgif-2-040811fbfd](https://user-images.githubusercontent.com/15524362/44275290-38d4ae80-a23c-11e8-9aa5-756dd1002e83.gif)

as you can see, the item that is coming onto/going off the screen remains at the same Y value, because the absolute limit from `transformItem()` is 1. My goal is to make it continue to go down to create the circular effect. Is it possible for the value of `position` to exceed the bounds of -1 < x < 1?

Thanks

**Comment by yarolegovich** [comment]
> I noticed in the DiscreteScrollLayoutTransformer that the getCenterRelativePositionOf() method returns a min of -1 and a max of 1, and it is being purposely limited, is there reasoning behind this?

Yes, I sure did this on purpose, limiting the range to [-1, 1] often simplifies work with animations.

I think [this method](https://github.com/yarolegovich/DiscreteScrollView/blob/master/library/src/main/java/com/yarolegovich/discretescrollview/DiscreteScrollView.java#L127) is what you're looking for.
