### ISSUE TITLE
Textview not growing based on the text size

### ISSUE THREAD

**Issue by Vaishnavi-optisol** [yarolegovich/DiscreteScrollView#133]
I have added custom layout like you do

<android.support.v7.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="290dp"
    android:id="@+id/cardView"
    android:layout_height="wrap_content"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_marginTop="@dimen/marginLeft"
    android:layout_marginBottom="@dimen/paddingTopLow"
    android:layout_gravity="center|top"
    app:cardElevation="10dp"
    app:cardCornerRadius="10dp">

 <TextView
            android:id="@+id/stepContent"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"/>

</android.support.v7.widget.CardView>

If I give wrap content then setting text via Recyclerview adapter shows only first line of the text. Works only if I give some default height then only I can see full text in the textview. Could you please help on this?

**Comment by yarolegovich** [comment]
Related to #20
