### ISSUE TITLE
How To Zoom the imageview of item_shop_card.xml

### ISSUE THREAD

**Issue by adilmushtaq1993** [yarolegovich/DiscreteScrollView#135]
Actually, I spend A lot of time to zoom in and zoom out to "item_shop_card.xml" layout image view but I am failed to do so.

Actually the image that come into the center i want to Zoom it

**Comment by yarolegovich** [comment]
Not sure I understood correctly but seems like you need to configure ScaleItemTransformer:
https://github.com/yarolegovich/DiscreteScrollView#transformations
The provided sample has the code you need.
