### ISSUE TITLE
Is it possible to overlap one item over other?

### ISSUE THREAD

**Issue by muhaym** [yarolegovich/DiscreteScrollView#137]
I am looking something like Cylindrical Effect, where we can see previous and next item, but partially under the current item.

**Comment by passself** [comment]
the same problem

**Comment by pwillmann** [comment]
see https://github.com/yarolegovich/DiscreteScrollView/issues/140#issuecomment-460842155

**Comment by yarolegovich** [comment]
A duplicate of https://github.com/yarolegovich/DiscreteScrollView/issues/140
