### ISSUE TITLE
Pre-binding adjacent items

### ISSUE THREAD

**Issue by sevar83** [yarolegovich/DiscreteScrollView#14]
Hi, is it possible to tweak the condition when an item view is laid out? My item view is fullscreen and that causes a little problem:

https://gifs.com/gif/58zJlZ

I need to bind the next item in background, that is - not just when a small edge of it becomes visible but earlier. In other words when item N becomes current item then at same time N+1 to be bound. As you can see from the video, my images are requested from network when the view appears, but that's too late. That should be done when the view is still off-screen. Is it possible to implement an "offscreen limit" like 1-2 items on both sides or to maintain an extra layout space like LinearLayoutManager does with https://developer.android.com/reference/android/support/v7/widget/LinearLayoutManager.html#getExtraLayoutSpace(android.support.v7.widget.RecyclerView.State)?

**Comment by yarolegovich** [comment]
Currently it is not possible. Will try to add the feature on this weekends.

**Comment by yarolegovich** [comment]
Hi. Try using the version 1.1.3 and a method:
```java
scrollView.setOffscreenItems(count);
```

**Comment by sevar83** [comment]
It works. Thank you very much.
