### ISSUE TITLE
Update to AndroidX 

### ISSUE THREAD

**Issue by bernaferrari** [yarolegovich/DiscreteScrollView#141]
Now released: https://developer.android.com/topic/libraries/support-library/androidx-overview

**Comment by searchy2** [comment]
This would be fantastic. I can make a PR for this but will it be accepted?

**Comment by bernaferrari** [comment]
I think it is worth trying. The developer has been very busy lately, and I think it will be easier for him to click on "accept" than do it himself.

**Comment by searchy2** [comment]
Let me look through my old commits. I think I updated one of his other libraries before so let me see if that was accepted.

**Comment by searchy2** [comment]
#143

**Comment by searchy2** [comment]
Submitted a PR with updates.

**Comment by mamatagelanee07** [comment]
@yarolegovich Can we please merge the pull request created by @searchy2? We are migrating to Android X and I just want to avoid add this library as a module in our app.

**Comment by gneokleous** [comment]
I have also created a PR with more recents updates around androidx and versions. https://github.com/yarolegovich/DiscreteScrollView/pull/179 

Can you have a look @yarolegovich ?

**Comment by yarolegovich** [comment]
Resolved with #134 and v1.5.0
