### ISSUE TITLE
Scroll like normal RecyclerView

### ISSUE THREAD

**Issue by qujc** [yarolegovich/DiscreteScrollView#150]
how to scroll like a normal RecyclerView, but not one by one item.

**Comment by JLu2138** [comment]
I have the same problem. Have you solved it？Can you tell me how to do it? thank you

> how to scroll like a normal RecyclerView, but not one by one item.

**Comment by markHervagault** [comment]
Same problem. I set : setSlideOnFling(true); and it's work for fast scroll but when I scroll slow, I only can scroll one by one item.

**Comment by yarolegovich** [comment]
The whole purpose of the library is its scroll behavior.
What you needed is a RecyclerView + ItemSnapHelper.
