### ISSUE TITLE
display only one item

### ISSUE THREAD

**Issue by LorenzoDD96** [yarolegovich/DiscreteScrollView#158]
i want to obtain exactly this (https://github.com/yarolegovich/DiscreteScrollView/blob/master/images/cards_shop.gif), 
but although I have followed your example of shop, i have only one item in my screen. 
could you help me with this problem?

**Comment by g19980115** [comment]
control item width

**Comment by jemshit** [comment]
@g19980115 how? item width is always `screenWidth/2` from my observation

**Comment by g19980115** [comment]
Sorry.The answer above is wrong. You should control the height of the DiscreteScrollView.

**Comment by yarolegovich** [comment]
I suppose the issue was with layout of your items.
A working sample of the shop example is provided.
