### ISSUE TITLE
Is pagination supported?

### ISSUE THREAD

**Issue by preyesm** [yarolegovich/DiscreteScrollView#164]
Hi, the library is really good, thanks for that. I wanted to know if we can implement endless scroll in the DiscreteScrollView library to support pagination

**Comment by HakorimanaEmmanuel** [comment]
me too i want to know

**Comment by yarolegovich** [comment]
A duplicate of:
https://github.com/yarolegovich/DiscreteScrollView/issues/169
The library provides callbacks necessary to implement pagination.
I think the feature is too case-specific.
