### ISSUE TITLE
ScaleTransform item width

### ISSUE THREAD

**Issue by jemshit** [yarolegovich/DiscreteScrollView#168]
Hi, it looks like when using ScaleTransform with `minScale`, item on the center uses `discreteScrollView/2` as width, and right, left items each uses 25%. Is there any way to change it? Or what part of the code decides it if i want to customize?

**Comment by masheransari** [comment]
@jemshit have you got any solution? because I am facing same issue in DiscreteScrollView in Horizontal when testing application in Tablet.

**Comment by jemshit** [comment]
i think it uses as much width as item width (give exact px width to items)
