### ISSUE TITLE
How to implement Pagination in DiscreteScrollView?

### ISSUE THREAD

**Issue by shahzi8285** [yarolegovich/DiscreteScrollView#169]
Hey I am using this wonderful library in my projects In one of my project I need to implement Paginations like onLoadMore with this library.

please help!

**Comment by RafaHDu** [comment]
Did you try with the normal RecyclerView Pagination?! I think you can achive that by using addOnScrollListener... I did not try that, but for example i use the OnClickListener of the RecyclerView in this library, so i think you can achive that.

I have not tested this, but i hope this can help in some way

        scrollView.addOnScrollListener(new RecyclerView.OnScrollListener() {
            @Override
            public void onScrollStateChanged(RecyclerView recyclerView, int newState) {
                super.onScrollStateChanged(recyclerView, newState);

                if (newState == AbsListView.OnScrollListener.SCROLL_STATE_TOUCH_SCROLL) {
                     //isScrolling becomes true when the user scrolls, so then the Data Fetch can be called
                    isScrolling = true;
                }

            }

            @Override
            public void onScrolled(RecyclerView recyclerView, int dx, int dy) {

                currentItems = layoutManager.getChildCount();
                totalItems = layoutManager.getItemCount();
                scrollOutItems = layoutManager.findFirstVisibleItemPosition();

                if (isScrolling && (currentItems + scrollOutItems == totalItems)) {

                    //DataService fetch
                    isScrolling = false;
                    fetchDataPopular();

                }

            }
        });

**Comment by yarolegovich** [comment]
Choose a callback suitable for your needs:
https://github.com/yarolegovich/DiscreteScrollView#callbacks
Then do something like:
```
void onCurrentItemChanged(@Nullable ViewHolder viewHolder, int position) {
   if (size - position <= ITEMS_LEFT_TO_LOAD_MORE) {
      loadMoreData();
   }
}
```
