### ISSUE TITLE
I can't show item first like demo | Don't want to show snap like image attach

### ISSUE THREAD

**Issue by VietBui93** [yarolegovich/DiscreteScrollView#174]
Please help me which way don't see left image when scroll to first item.
Many thanks for any helping.
![can't show like demo](https://user-images.githubusercontent.com/13973256/60697587-3abb6500-9f15-11e9-97ee-2d9da1e5cd27.jpg)

**Comment by hoanv810** [comment]
@VietBui93 You should not use InfiniteScrollAdapter for your RecyclerView

**Comment by xiakehe** [comment]
i have the same problem . don't show the left item and right item  
i used InfiniteScrollAdapter

**Comment by yarolegovich** [comment]
That's how InfiniteScrollAdapter supposed to work.
