### ISSUE TITLE
ScrollListener triggering while swiping up on itemView

### ISSUE THREAD

**Issue by agonavd** [yarolegovich/DiscreteScrollView#182]
I have a conflict with scrollListener of the recyclerView and my onTouchListener i added for the itemView.

When I try to swipeUp in the cardview it triggers the scrollListener of recyclerview instead of the onTouchListener i use to recognize the swipeUp in the itemView.

**Comment by yarolegovich** [comment]
That's how RecyclerView processes touch, the library has nothing to do with it.
I supposed what you need it not a touch listener but a parent that intercepts touches.
