### ISSUE TITLE
Show number of items on screen, like in the second gif. I cant get to show previous and next items partially

### ISSUE THREAD

**Issue by logan033** [yarolegovich/DiscreteScrollView#186]
I want to show exactly 3 items on the screen at a time, but only one item is showing at a time.
How can achieve that? and also how to show next and previous items partially

**Comment by yarolegovich** [comment]
If your item size should depend on screen size, you need to handle this in your onCreateViewHolder updating LayoutParams of a created view to be equal to something like`(screenWidth - gapsBetweenItems) / numberOfItemsToBeVisible`.
