### ISSUE TITLE
 adapter item content changed, but DiscreteScrollView size not change

### ISSUE THREAD

**Issue by zhangxh2000** [yarolegovich/DiscreteScrollView#187]
I used DiscreteScrollView,the item view is something like this 
<android.support.constraint.ConstraintLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    >
    <ImageView/>
    <TextView1/>
    <TextView2/>
</android.support.constraint.ConstraintLayout>
if I set the TextView1's visiablity to gone, the item view's total height should be changed,but actually,
the height not change,TextView1 disappeared ,TextView2 lift up and there is gap between TextView2 and the parent bottom(parent height not change).I have replaced DiscreteScrollView with RecyclerView, and the height can change according TextView1's visiablity,so there seems something wrong in DiscreteScrollView

**Comment by yarolegovich** [comment]
Not enough detail, but most probably related to #20
