### ISSUE TITLE
getAdapterPosition() returning random long number.

### ISSUE THREAD

**Issue by elblogbruno** [yarolegovich/DiscreteScrollView#188]
I'm using this code on my adapter.

        @Override
        public void onClick(View v) {
            if (listener != null) {
                int position = getAdapterPosition();
                if (position != RecyclerView.NO_POSITION) {
                    listener.onItemClick(notifications.get(position));
                }
            }
        }

The getAdapterPosition() is returning a long number giving me this error of course, as the size of the list is 49 not a long number like 1073741823. 

`java.lang.IndexOutOfBoundsException: Index: 1073741823, Size: 49
        at java.util.ArrayList.get(ArrayList.java:437)`

I've tried passing the  DiscreteScrollView itemPicker onto my listener and changing to  
`int position = itemPicker.getCurrentItem(); `
no luck.

It is an android bug or this plugin's bug?. Please help me out!

**Comment by yarolegovich** [comment]
I suppose you're using InfiniteScrollAdapter.
It's in the docs how to get the real position.
https://github.com/yarolegovich/DiscreteScrollView#infinite-scroll
