### ISSUE TITLE
How to disable user to swipe left or right or both

### ISSUE THREAD

**Issue by faraksoch1881** [yarolegovich/DiscreteScrollView#189]
How to disable scrollview to swipe left or right or both?Since I'm using Next and Previous button, I want to swipe to next or previous using button only and disable user to swipe left or right. I searched for but couldn't find it. I will really appreciate it if you could help me

**Comment by yarolegovich** [comment]
Added in v1.5.1 https://github.com/yarolegovich/DiscreteScrollView#disabling-scroll
