### ISSUE TITLE
setOffscreenItems doesn't work

### ISSUE THREAD

**Issue by LoveNormalDay** [yarolegovich/DiscreteScrollView#19]
Hello.
I want to use setOffscreenItems ,but it doesn't work.Can you tell me why,thank you very much

**Comment by yarolegovich** [comment]
Tell me please what are you trying to achieve and what doesn't work.

**Comment by LoveNormalDay** [comment]
Thank you for your reply.What I wanted was the effect that infinite loop,but I does not know how to achieve  it.So I used many groups had the same data to achieve infinite loop.If you can do it,please tell me ,thanks

**Comment by yarolegovich** [comment]
`.setOffscreenItems(n)` just makes LayoutManager to measure and lay out n items that are not yet visible on the screen.
What you want is a newly added feature described [here](https://github.com/yarolegovich/DiscreteScrollView#infinite-scroll). Switch to version `1.2.0` to use it.

**Comment by LoveNormalDay** [comment]
Thank you very much
