### ISSUE TITLE
ScaleTransformer not transforming uniformly

### ISSUE THREAD

**Issue by arpanbag001** [yarolegovich/DiscreteScrollView#194]
While using ScaleTransformer maxScale or minScale, the on screen non-current items are not getting transformed uniformly! The left (prev) item to the current item always becomes slightly larger (few dp) than all the other non-current items.
In the sample app, the difference is 1dp, but in my setup (item size: 44dp, setMaxScale: 1.5f ), the difference is around 7dp, which is very much noticeable.

**Comment by yarolegovich** [comment]
Fixed in v1.5.1
