### ISSUE TITLE
Make an AsyncTask call in a specific slider

### ISSUE THREAD

**Issue by GiacomoSilli** [yarolegovich/DiscreteScrollView#195]
How do I identify the current slider to make an AsyncTask call? I have tried several methods but without success.

Specifically I have two AsyncTask calls to run in the created slider.

The first call must be made in the first slider, the second call must be made in the second, nothing in the other sliders.

Using methods like `onscroll()` or `onItemChanged()` I can't achieve the desired result.

The first call is also made in the second slider, or the content of the second call is also displayed in the first slider etc.

How can I precisely identify the current position and make an AsyncTask call in that exact slider? Thank you

**Comment by yarolegovich** [comment]
Hi.
That doesn't seem related to the library in any way, more like to how you've structured your presentation layer. 
You can set two independent listeners or a single listener and launch your async jobs when either of two views changes the selection.
By keeping references to your views you can now the exact selection - `getCurrentItem` call.
