### ISSUE TITLE
jcenter error

### ISSUE THREAD

**Issue by m5kh6n77** [yarolegovich/DiscreteScrollView#209]
Hello! Your library is published only to jcenter. Please consider publishing it also to mavenCentral, as jcenter is shutting down in May.

Here is some info on how to publish artifacts to mavenCentral.

**Comment by kharolpooran** [comment]
Please consider it as a priority people are using your library.

**Comment by lester-osimdev** [comment]
@m5kh6n77 @kharolpooran Please use this at the moment
```
allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
```
```
dependencies {
	        implementation 'com.github.yarolegovich:DiscreteScrollView:v1.5.1'
	}
```

**Comment by m5kh6n77** [comment]
> 
> 
> @m5kh6n77 @kharolpooran Please use this at the moment
> 
> ```
> allprojects {
> 		repositories {
> 			...
> 			maven { url 'https://jitpack.io' }
> 		}
> 	}
> ```
> 
> ```
> dependencies {
> 	        implementation 'com.github.yarolegovich:DiscreteScrollView:v1.5.1'
> 	}
> ```

thank you

**Comment by carlos-mg89** [comment]
It works for the old `com.yarolegovich:discrete-scrollview:v1.4.9` version as well.

Simply replace this:

`implementation 'com.yarolegovich:discrete-scrollview:v1.4.9'`

with this:

`implementation 'com.github.yarolegovich:DiscreteScrollView:v1.5.1'`

Just tested it, and there doesn't seem to be any breaking change.

Perhaps this could be written in the README so people coming from the old 1.4 version know they can easily update to the 1.5.
