### ISSUE TITLE
How to scroll through more than one item?

### ISSUE THREAD

**Issue by timshinlee** [yarolegovich/DiscreteScrollView#21]
Now I can only scroll through one item at a time, then it stops scrolling. Is there any way to scroll through multiple items at one scrolling? I call this method smoothScrollToPosition() when users tap on a item to achieve this. But when users slide left or right, only one item and then stops. Thanks!

**Comment by sevar83** [comment]
Speaking strictly the gesture you describe is not scroll but "fling". If it's not too late I suggest you to try overriding `DiscreteLayoutManager.onFling()` and/or `getHowMuchIsLeftToScroll()`.

**Comment by timshinlee** [comment]
@sevar83 Nice! You are right about fling. Thanks for your answer! I will try it out immediately.

**Comment by timshinlee** [comment]
@sevar83 Pity the `DiscreteLayoutManager` is not public. Is adding this library as module and making `DiscreteLayoutManager` public the only way to achieve this? I wonder why the author prefer not to make `DiscreteLayoutManager` public while offering `DiscreteScrollView.setLayoutManger(DiscreteScrollLayoutManager layoutManager)`?

**Comment by bnottingham** [comment]
@timshinlee were you able to solve this issue, this library is perfect except for being able to scroll through more than one item at a time.

**Comment by timshinlee** [comment]
@bnottingham Sorry. I tried but can't figure it out. @yarolegovich Would you consider adding fling through multiple items as a new feature?

**Comment by yarolegovich** [comment]
How do you propose to determine an amount of positions to scroll through? 
Btw, I will be really happy to review and accept a pull request with this feature.

**Comment by timshinlee** [comment]
@yarolegovich Sorry I am not familiar enough with the scrolling mechanism to pull a solution request. 
But just like RecyclerView itself or ListView, they can continue scrolling over certain distances after the finger flings. 
I think using velocity to determine the amount of positions may be feasible.

**Comment by srujan7** [comment]
@timshinlee  absolutely. Velocity can be decided to determine the amount of positions. @yarolegovich I tried to solve it but didn't succeed yet. Still trying though but I doubt to succeed. Even I'm dealing with the scrolling mechanism for the first time. You must have known all the tits-bits of the code. Can you either help or implement it yourself? For many this is the only lacking feature in the library. :)

**Comment by srujan7** [comment]
Oh wait! I just achieved it!

**Comment by gr3ger** [comment]
Post your findings or make a merge request later please :3 I'm trying to get this to work as well.

**Comment by srujan7** [comment]
Give me few hours guys will make a pull req.  ✌

**Comment by srujan7** [comment]
Requested to merge. One can  just download [my repo](https://github.com/srujan7/DiscreteScrollView) for urgent use. Let me know of results.

**Comment by timshinlee** [comment]
@srujan7 Good job! Works like magic. Is it possible to furthermore allow sliding of multiple views on the drag gesture?

**Comment by hemanthkaipaa** [comment]
I've wasted 4 days of my time..! I didn't checked library issues..? its pity, I am about to raise this scroll issue Thank you Srujan..!

**Comment by whathegithub** [comment]
@srujan7 Good job!

**Comment by yarolegovich** [comment]
Closed via 34b23fc5be792e4105763563cf30ecf07514cb2b

**Comment by timshinlee** [comment]
Thanks a lot!
