### ISSUE TITLE
Delete item error

### ISSUE THREAD

**Issue by wkq87** [yarolegovich/DiscreteScrollView#22]
When i want to delete recyclerview item，it cannot work correct.
i delete the last item,an call notifyDataSetChanged method，and the recyclerview show incorrectly;all items scroll to the right of the center.
but when i delete other position items，it work well.

**Comment by yarolegovich** [comment]
Please call `notifyItemRemoved`, my implementation of `notifyDataSetChanged` doesn't know how to shift `currentPosition`, so it resets it.
