### ISSUE TITLE
How to dynamically control item width

### ISSUE THREAD

**Issue by zhangle1** [yarolegovich/DiscreteScrollView#23]
I want to get the screen width -10dp as the width of item,
I tried doing it in onCreateViewHolder:
        viewHolder= new viewHolder(_inflate);
        ViewGroup.LayoutParams _layoutParams = viewHolder.mCardView.getLayoutParams();
        layoutParams.width=_layoutParams.width-10;
        viewHolder.mCardView.setLayoutParams(_layoutParams);
But it doesn't work.

**Comment by sevar83** [comment]
I could suggest you to use `match_parent` as the item size and then apply the min/max scale. But you'll have to calculate the desired scale based on the measured item size.

**Comment by zhangle1** [comment]
thanks,I still have some questions about how I should control the position of item so that the second item can display an optional value

**Comment by yarolegovich** [comment]
Probably related to #20
