### ISSUE TITLE
Scrolling problems with async remote images

### ISSUE THREAD

**Issue by coanag** [yarolegovich/DiscreteScrollView#28]
Hi,
im facing issues with scrolling its not smooth and when scrolling feels like "it's trying hard" to scroll to the next element.
I feed my recycle adapter with remote data and all images are loading remotely with glide.
The orientation of the descreteScrollview is horizontal.

Can someone please recommend, some fixes for smooth scrolling.

Thanks in advance.

**Comment by yarolegovich** [comment]
I'm closing the issue until there are more similar reports. Async image loading is implemented in [the sample](https://github.com/yarolegovich/DiscreteScrollView/tree/master/sample) and seems to work fine.
