### ISSUE TITLE
Vertical Scroll

### ISSUE THREAD

**Issue by andanicalik** [yarolegovich/DiscreteScrollView#3]
Can you add vertical scroll support or How can I do?

**Comment by andanicalik** [comment]
Thank you for your interest. I want to do like [this](https://github.com/awdigital/AWCollectionViewSlidingDoors) library. Rows height will be fixed. And focused row alpha will higher than other.

**Comment by yarolegovich** [comment]
I've added support for vertical orientation, but don't think it will allow you to create a view similar to the library you showed me. 
I will updated the docs today, also you can check how vertical orientation works in sample - package gallery.

**Comment by andanicalik** [comment]
Thank you. I have one more question. When I scroll it swipe one by one. Can it swipe more than one item at fastly scroll ?

**Comment by yarolegovich** [comment]
No, it can't.
