### ISSUE TITLE
how to change the margin of neighbouring items?

### ISSUE THREAD

**Issue by gmfbilu** [yarolegovich/DiscreteScrollView#30]
NO OnItemClickListener?

**Comment by ronanhardiman** [comment]
`android:layout_margin="10dp"`
in the itemView can effect

**Comment by gmfbilu** [comment]
i mean the gap between two items

**Comment by ronanhardiman** [comment]
try it and you will see the effect.

**Comment by yarolegovich** [comment]
@ronanhardiman is correct. By changing your layout.
