### ISSUE TITLE
Horizontal scrolling within ViewPager fragment not working correctly

### ISSUE THREAD

**Issue by jdrexha** [yarolegovich/DiscreteScrollView#31]
Hi,

I have a ViewPager set up with 3 fragments. The 3rd fragment, contains a relativeLayout with the DiscreteScrollView located in the lower half.

The general implementation works fine, displays correctly, transforms etc. However, when it comes to scrolling, if you try a quick "fling" type scroll, it does not register on the DiscreteScrollView, instead, the ViewPager takes the touch event. If you however, hold your finger over an item in the DiscreteScrollView for a split second or more, and then attempt to scroll, it works fine. This also occurs if you very casually or "slowly" attempt to scroll (possibly due to the split-second extra contact over the DiscreteScrollView,allowing the touch to be registered for the DiscreteScrollView instead of the ViewPager). Furthermore, if you initially scroll up or down to initial the contact - without lifting your finger - and then scrolling horizontally, it also works every time.

I have tested this on various devices with the same result. I believe there's a problem with the initial touch registration for the DiscreteScrollView.  Could this be a problem with the internal LayoutManager and how it handles scrolls?

As previously, we had a standard recyclerView in the exact same location and setup and it handled the scrolling flawlessly as would be expected for such a trivial aspect.

We have tried various properties, enabling and disabling NestedScrolling, various layout formats (such as using NestedScrollViews), nothing made any difference at all.

Any help or insight into this at all would be greatly appreciated!

**Comment by parcool** [comment]
add this code to DiscreteScrollView.java ```    @Override
    public boolean canScrollHorizontally(int direction) {
        return true;
    }```

**Comment by yarolegovich** [comment]
I understand it's way too late and I'm really sorry I didn't help.
The issue existed because there was no implementation of `LayoutManager` scroll APIs (5ed5c2e8c9d04a3dc80ac546adfa5407f6e08be4).
Closed as a part of #77.
