### ISSUE TITLE
compile Version problem for this library  

### ISSUE THREAD

**Issue by kedartorase** [yarolegovich/DiscreteScrollView#32]
compile Version problem for this library   giving error

**Comment by yarolegovich** [comment]
Always post the error you're talking about.

**Comment by sakshamsd** [comment]
Error:Failed to resolve: com.android.support:appcompat-v7:26.0.0
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:C:/Users/Admin/AndroidStudioProjects/Classic/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by yarolegovich** [comment]
See #55
