### ISSUE TITLE
requiresFadingEdge doesn't work

### ISSUE THREAD

**Issue by HusseinElFeky** [yarolegovich/DiscreteScrollView#34]
I tried adding `android:requiresFadingEdge="vertical|horizontal"` to `DiscreteScrollView` in xml, but it had no effect. How can I add fading edge to it?

**Comment by yarolegovich** [comment]
If you meant a fading edge which appears during overscroll, then it's enabled by default. In `1.4.3` I added an API to disable the effect via xml:
```xml
android:overScrollMode="never"
```
and programmatically:
```java
scrollView.setOverScrollEnabled(false);
```
