### ISSUE TITLE
How to decrease the space between items?

### ISSUE THREAD

**Issue by ZeeshanShabbir** [yarolegovich/DiscreteScrollView#35]
Hey. I must say that this is a very interesting library. Good work guys. But i am having hard time to decrease the space between recycler items. I want to decrease the space please look at this below image.

![capture](https://user-images.githubusercontent.com/14093715/28619099-466d1656-7220-11e7-940c-ec7165b3750f.PNG)

What i have tried so far is below.
This is the item decorator.

`  public class RecyclerItemDecorator extends RecyclerView.ItemDecoration {

    @Override
    public void getItemOffsets(Rect outRect, View view, RecyclerView parent, RecyclerView.State state) {
        outRect.left = 0;
        outRect.right = 0;
        outRect.top = 0;
        outRect.bottom = 0;
        //super.getItemOffsets(outRect, view, parent, state);
    }
    }
`
Here is the java code from activity

`binding.rcTest.addItemDecoration(new RecyclerItemDecorator());`

**Comment by ZeeshanShabbir** [comment]
Didn't know negative offset would work.  

```
@Override
public void getItemOffsets(Rect outRect, View view, RecyclerView parent, RecyclerView.State state) {
    outRect.left = -50;
    outRect.right = -50;
    outRect.top = 0;
    outRect.bottom = 0;
    //super.getItemOffsets(outRect, view, parent, state);
}
}
```

This solved my problem but i had to test it on different screen sizes.

**Comment by yarolegovich** [comment]
For it to work on different scree sizes I advice to multiply your offset by screen density, like for example:
```java
outRect.right = view.getResources().getDisplayMetrics().density * 12;
```
