### ISSUE TITLE
Help: Gradual zoom decrease

### ISSUE THREAD

**Issue by aresares** [yarolegovich/DiscreteScrollView#37]
Hi, is there a way to decrease zoom gradualy among items for example the current item in list is the most zoomed  now what I mean is to zoom also adiacent items for example by 50% then others by 25% ecc...

**Comment by yarolegovich** [comment]
Hi. Unfortunately that's not possible now.

**Comment by yarolegovich** [comment]
Implemented in `1.4.2` and updated [the docs](https://github.com/yarolegovich/DiscreteScrollView#transformations).
