### ISSUE TITLE
onScroll() method from ScrollStateChangeListener called with incorrect params when call smoothScrollToPosition()

### ISSUE THREAD

**Issue by bagrusss** [yarolegovich/DiscreteScrollView#38]
When I call `srollView.smoothScrollToPosition(pos)` and difference between `pos` and old position, for example, is 2 I got this results in CatLog:

    08-05 18:18:38.818 20927-20927/com.some D/CropFormAdapter: onScrollStart() 0
    08-05 18:18:38.835 20927-20927/com.some D/CropFormAdapter: onScroll() currentHolder = 0 newCurrentHolder = 1 scrollPosition = -0.14285715
    08-05 18:18:38.852 20927-20927/com.some D/CropFormAdapter: onScroll() currentHolder = 0 newCurrentHolder = 1 scrollPosition = -0.2857143
    08-05 18:18:38.868 20927-20927/com.some D/CropFormAdapter: onScroll() currentHolder = 0 newCurrentHolder = 1 scrollPosition = -0.42380953
    08-05 18:18:38.885 20927-20927/com.some D/CropFormAdapter: onScroll() currentHolder = 0 newCurrentHolder = 1 scrollPosition = -0.54761904
    08-05 18:18:38.901 20927-20927/com.some D/CropFormAdapter: onScroll() currentHolder = 0 newCurrentHolder = 1 scrollPosition = -0.67142856
    08-05 18:18:38.918 20927-20927/com.some D/CropFormAdapter: onScroll() currentHolder = 0 newCurrentHolder = 1 scrollPosition = -0.78571427
    08-05 18:18:38.935 20927-20927/com.some D/CropFormAdapter: onScroll() currentHolder = 0 newCurrentHolder = 1 scrollPosition = -0.9047619
    08-05 18:18:38.951 20927-20927/com.some D/CropFormAdapter: onScroll() currentHolder = 0 newCurrentHolder = 1 scrollPosition = -1.0
    08-05 18:18:38.969 20927-20927/com.some D/CropFormAdapter: onScroll() currentHolder = 0 newCurrentHolder = 1 scrollPosition = -1.0
    08-05 18:18:38.985 20927-20927/com.some D/CropFormAdapter: onScroll() currentHolder = 0 newCurrentHolder = 1 scrollPosition = -1.0
    08-05 18:18:39.000 20927-20927/com.some D/CropFormAdapter: onScroll() currentHolder = 0 newCurrentHolder = 1 scrollPosition = -1.0
    08-05 18:18:39.017 20927-20927/com.some D/CropFormAdapter: onScroll() currentHolder = 0 newCurrentHolder = 1 scrollPosition = -1.0
    08-05 18:18:39.033 20927-20927/com.some D/CropFormAdapter: onScroll() currentHolder = 0 newCurrentHolder = 1 scrollPosition = -1.0
    08-05 18:18:39.051 20927-20927/com.some D/CropFormAdapter: onScroll() currentHolder = 0 newCurrentHolder = 1 scrollPosition = -1.0
    08-05 18:18:39.066 20927-20927/com.some D/CropFormAdapter: onScroll() currentHolder = 0 newCurrentHolder = 1 scrollPosition = -1.0
    08-05 18:18:39.084 20927-20927/com.some D/CropFormAdapter: onScroll() currentHolder = 0 newCurrentHolder = 1 scrollPosition = -1.0
    08-05 18:18:39.099 20927-20927/com.some D/CropFormAdapter: onScroll() currentHolder = 0 newCurrentHolder = 1 scrollPosition = -1.0
    08-05 18:18:39.117 20927-20927/com.some D/CropFormAdapter: onScroll() currentHolder = 0 newCurrentHolder = 1 scrollPosition = -1.0
    08-05 18:18:39.133 20927-20927/com.some D/CropFormAdapter: onScroll() currentHolder = 0 newCurrentHolder = 1 scrollPosition = -1.0
    08-05 18:18:39.150 20927-20927/com.some D/CropFormAdapter: onScroll() currentHolder = 0 newCurrentHolder = 1 scrollPosition = -1.0
    08-05 18:18:39.167 20927-20927/com.some D/CropFormAdapter: onScroll() currentHolder = 0 newCurrentHolder = 1 scrollPosition = -1.0
    08-05 18:18:39.184 20927-20927/com.some D/CropFormAdapter: onScroll() currentHolder = 0 newCurrentHolder = 1 scrollPosition = -1.0
    08-05 18:18:39.200 20927-20927/com.some D/CropFormAdapter: onScroll() currentHolder = 0 newCurrentHolder = 1 scrollPosition = -1.0
    08-05 18:18:39.215 20927-20927/com.some D/CropFormAdapter: onScroll() currentHolder = 0 newCurrentHolder = 1 scrollPosition = -1.0
    08-05 18:18:39.233 20927-20927/com.some D/CropFormAdapter: onScroll() currentHolder = 0 newCurrentHolder = 1 scrollPosition = -1.0
    08-05 18:18:39.249 20927-20927/com.some D/CropFormAdapter: onScroll() currentHolder = 0 newCurrentHolder = 1 scrollPosition = -1.0
    08-05 18:18:39.266 20927-20927/com.some D/CropFormAdapter: onScroll() currentHolder = 0 newCurrentHolder = 1 scrollPosition = -1.0 

When scroll started between 0 and 1 positions - ok, but when the scroll goes between 1 and 2 positions I got the incorrect viewHolders objects in the callback parameters (they have 0 and 1 positions, when I expected to get viewHolders with 1 and 2 positions), and scrollPosition in this case is always -1.0 (08-05 18:18:38.969) in the logs.

[my code](https://gist.github.com/bagrusss/40d28f017befa3e8420c1f300fa68898)

**Comment by xm3366336** [comment]
me too...
