### ISSUE TITLE
Sliding direction

### ISSUE THREAD

**Issue by dzzchao** [yarolegovich/DiscreteScrollView#4]
Hi, Your project is sliding from the left to the right, I want to change from the right to the left slide, can you tell me how to do it? And I do not want to use DiscreteScrollView.scrollToPostion () this method to directly display the last one of the data, and then slide from the right to achieve this. Can you help me?

**Comment by yarolegovich** [comment]
Hi. Currently the library doesn't have any special support for it. Can you tell me please what exactly you want to achieve and why scrollToPosition() doesn't solve the problem?

**Comment by dzzchao** [comment]
Sorry, I did not look at the source code yesterday, and now I know how to do it, thank you.
