### ISSUE TITLE
InfiniteScrollAdapter incorrect position detection

### ISSUE THREAD

**Issue by jjhesk** [yarolegovich/DiscreteScrollView#41]
InfiniteScrollAdapter does pick up the position if there are only three items in the adapter. Using get real position from the adapter.

**Comment by yarolegovich** [comment]
Provide please more details.

**Comment by yarolegovich** [comment]
I'm closing the issue, because it's a single issue report and everything works perfectly fine in the [sample app](https://github.com/yarolegovich/DiscreteScrollView/tree/master/sample).

**Comment by Dreyar** [comment]
I'm having the same problem and the problem also appears in the sample app. More specific, on ShopActivity: 

carouselView.addScrollListener(new DiscreteScrollView.ScrollListener<RecyclerView.ViewHolder>() {
            @Override
            public void onScroll(float scrollPosition, int currentPosition, int newPosition, @Nullable RecyclerView.ViewHolder currentHolder, @Nullable RecyclerView.ViewHolder newCurrent) {
                int realPosition = infiniteAdapter.getRealPosition(carouselView.getCurrentItem());
                if (scrollPosition == 1f || scrollPosition == -1f)
                    Log.d("currentPosition", String.valueOf(realPosition));
            }
        });

I can also provide some code from my personal project if needed! @yarolegovich
