### ISSUE TITLE
Maybe there is mistake into fling algorithm

### ISSUE THREAD

**Issue by NZeee** [yarolegovich/DiscreteScrollView#48]
Sorry for my English. I use vertical scrollview, but i could not make it to work with fling. Then, i looked in the code and saw that:

https://github.com/yarolegovich/DiscreteScrollView/blob/bd07e7bf5e210d90aef5c240276b22de475ee490/library/src/main/java/com/yarolegovich/discretescrollview/DiscreteScrollLayoutManager.java#L414-L416

I suggest that there should be 
Math.abs(velocity/flingThreshold)
instead of
Math.abs(velocityX/flingThreshold)

**Comment by yarolegovich** [comment]
You're absolutely right, I wasn't attentive enough when accepted #26.
