### ISSUE TITLE
DiscreteScrollLayoutManager is package private

### ISSUE THREAD

**Issue by simur407** [yarolegovich/DiscreteScrollView#49]
I spotted that if I want create my own LayoutManager, I have to extend DiscreteScrollLayoutManager and this is reasonable, but I saw that this class is package private, so I can't extend it. Is this intended?

**Comment by yarolegovich** [comment]
Yeah, I thought that hiding implementation details is a good idea. But soon there will be a new inheritance-friendly version (with majority of fields and methods made protected to be visible for testing).

**Comment by yarolegovich** [comment]
Well, I decided not to do it. 
If customization is required, I advice to create a new fork of the repository and use the fork in you project.
