### ISSUE TITLE
Child Item loaded problem.

### ISSUE THREAD

**Issue by NullKnot** [yarolegovich/DiscreteScrollView#5]
Hello, thanks for this great library.
It looks really nice 👍 

But I found that will be laggy when we have more data on it.
I try to figure out, then I found that the DiscreteScrollView will load "all child item" when init.
So if all of my data(picture) are different, it will cause laggy and even out of memory.

My question is that why DiscreteScrollView need to loaded "all child item" and keep them?
Is it necessary or for some unknown reason?

Looking forward to your reply.
Thanks again : D

**Comment by yarolegovich** [comment]
Hi, thanks a lot. I made a terrible mistake in logic and spoiled the whole idea of the library. Will deliver a fix soon.

**Comment by yarolegovich** [comment]
Use please the version 1.1.1, this horrible bug is fixed in it. Now only visible views are added to layout. 
Thanks again for pointing out the issue.

**Comment by NullKnot** [comment]
Wow!
I will try the new version.
Thank for you fix the bug so quickly :D
