### ISSUE TITLE
Set non-selectable items?

### ISSUE THREAD

**Issue by jintoga** [yarolegovich/DiscreteScrollView#54]
Good day, thanks for your awesome library! Is there any way i can achieve this behavior where some items are not selectable? I mean what i'm trying to do is when i scroll to that particular position(that should not be selected), the DSV automatically scroll to other position. I already tried to do it with onScrollEnd and achieved what i wanted, but sometimes the position still get selected.

**Comment by yarolegovich** [comment]
Hi. Unfortunately the lib doesn't support such feature.

**Comment by jintoga** [comment]
I managed to achieve what i was looking for. Thanks for your answer!
