### ISSUE TITLE
Not working with android Appcompat

### ISSUE THREAD

**Issue by Inzimam-Tariq** [yarolegovich/DiscreteScrollView#55]
I'm using android appcompat lib and when I try to add this lib in gradle file under dependencies on sync android studio give an error for support libraries like appcompat, recyclerview etc.
This is what I get on sync
```
Error:Failed to resolve: com.android.support:appcompat-v7:26.0.0
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:E:/Android_Studio_and_SDK/Opencart_android/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
```
And this
```
Error:Failed to resolve: com.android.support:recyclerview-v7:26.0.0
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:E:/Android_Studio_and_SDK/Opencart_android/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
```

But when I remove this lib (DiscreteScrollView) everything is work fine as usual. I tried more than once.
I'm using 

1. Android studio 2.3.3

2. gradle-3.3

3.  Java 8

**Comment by yarolegovich** [comment]
You can exclude library dependencies, if they are present in your project:
```java
compile ('com.yarolegovich:discrete-scrollview:1.3.0') {
   exclude group: 'com.android.support'
}
```

**Comment by yarolegovich** [comment]
Either install a repository, as advised in the error message, or provide all library's dependencies of your preferred versions and use:
```java
compile ('com.yarolegovich:discrete-scrollview:1.3.0') {
   transitive = false
   //or
   exclude group: 'com.android.support'
}
```
