### ISSUE TITLE
Item size has to be fixed in discrete scrollview

### ISSUE THREAD

**Issue by archit2495** [yarolegovich/DiscreteScrollView#58]
The items that are to be displayed inside the discrete scrollview the size has to be predefined and cannot be set as match_parent.

**Comment by yarolegovich** [comment]
It can be set as `match_parent` or `wrap_content`, however it's dependent on the size of the first item. I assume the issue is a duplicate of #20

**Comment by bhylak** [comment]
Setting match_parent for all of the items didn't work.
