### ISSUE TITLE
scrollToPosition always scroll to last element

### ISSUE THREAD

**Issue by olmur** [yarolegovich/DiscreteScrollView#59]
I tried 1.2.0, 1.3.0 and 1.3.1 versions of the library but effect is the same. When I use scrollToPosition it always scroll to the last item. 

`
            photoList.clear();
            photoList.addAll(newAssetList);

        if (diffResult != null) {
            diffResult.dispatchUpdatesTo(this);
        } else {
            notifyDataSetChanged();
        }
        recyclerView.scrollToPosition(selectedItemPosition);
 `

selectedItemPosition is correct.

Could u help to figure out what is the problem please?

**Comment by olmur** [comment]
I found the reason.. Will post solution and pr with fix  later.

**Comment by yarolegovich** [comment]
I have [two correct test cases](https://github.com/yarolegovich/DiscreteScrollView/blob/master/library/src/androidTest/java/com/yarolegovich/discretescrollview/DataSetModificationTest.java#L239) which model this scenario.
I will appreciate much if someone adds a failing one.

**Comment by agustinsivoplas** [comment]
@olmur do you have a solution for this? I would like to scroll always to first element
