### ISSUE TITLE
How to reduce the spacing between view-in-focus and view in background in horizontal mode?

### ISSUE THREAD

**Issue by abhiank209** [yarolegovich/DiscreteScrollView#6]
Hello, 

I'm trying to emulate something which looks like the shop cards demo in your sample app. However, I'm trying to reduce the spacing between the view which is expanded and the view which is in the background. How can I do this?

Btw, thanks for building this nice library.

**Comment by yarolegovich** [comment]
Hi. 
If you have margins on root elements, remove them. 
If it doesn't help, write your custom [transformer](https://github.com/yarolegovich/DiscreteScrollView/blob/master/library/src/main/java/com/yarolegovich/discretescrollview/transform/ScaleTransformer.java) that will also shift view to the right/left depending on position or just play with pivots: 
```java
Pivot pivotX = position > 0 Pivot.X.LEFT : Pivot.X.RIGHT;
pivotX.setOn(item);
Pivot.Y.CENTER.setOn(item);
float closenessToCenter = 1f - Math.abs(position);
float scale = minScale + maxMinDiff * closenessToCenter;
item.setScaleX(scale);
item.setScaleY(scale);
```

**Comment by abhiank209** [comment]
Cool. Thanks a lot. Will try out a custom transformer.

**Comment by vipulasri** [comment]
@abhiank209 were you able to implement custom transformer?
