### ISSUE TITLE
How to open auto scroll..

### ISSUE THREAD

**Issue by devzwy** [yarolegovich/DiscreteScrollView#65]

**Comment by yarolegovich** [comment]
It's always a good idea to read [the docs](https://github.com/yarolegovich/DiscreteScrollView#related-to-the-current-item) or check [the sample](https://github.com/yarolegovich/DiscreteScrollView/blob/master/sample/src/main/java/com/yarolegovich/discretescrollview/sample/DiscreteScrollViewOptions.java#L74).
