### ISSUE TITLE
wrong currentposition  newposition number

### ISSUE THREAD

**Issue by liuyusen1986** [yarolegovich/DiscreteScrollView#66]
I want to get currentposition  and newposition number  because this contact with my map    who have marker info on it ,marker info can choosed or unchoosed  while  this discreteScrollview  item iamge show or  disshow,  my  data  source  which map marker data size  is same with  discreteScrollview data size   ,so they can  show  corresponding  but the   log info  show  position  is not right  :
i dot konw whether next is  the right  listener which i use:
```java
itemPicker.addScrollListener(new DiscreteScrollView.ScrollListener<RecyclerView.ViewHolder>() {
            @Override
            public void onScroll(float scrollPosition, int currentPosition, int newPosition, @Nullable RecyclerView.ViewHolder currentHolder, @Nullable RecyclerView.ViewHolder newCurrent) {
              Toast.makeText(HomeActivity.this,scrollPosition+" "+currentPosition+" "+newPosition,Toast.LENGTH_SHORT).show();
                markerMapOld = newPosition;
                //  MRKER INFO : 1,还原当前的position信息   2.下一个进行改变
//                Marker marker = markerMap.get(dotList.get(currentPosition%dotList.size()).getDotId());
                Marker marker = markerMap.get(dotList.get(currentPosition%dotList.size()).getDotId());
                marker.remove();
```

**Comment by yarolegovich** [comment]
I don't understand what's actually wrong. 
Suppose that's how your list looks in the rest state. 
0 -- 1 -- 2
If we scroll it a bit to the right, it will become:
--1--2-
And your listener will provide you with currentPosition=1, newPosition=2.
Of if we scroll the list to the left:
-0--1--
currentPosition=1, newPosition=0.
