### ISSUE TITLE
Orientation deprecated in support library 27.0.1

### ISSUE THREAD

**Issue by farzadnone** [yarolegovich/DiscreteScrollView#67]
Orientation deprecated in **com.android.support:recyclerview-v7:27.0.1**. please update library.

**Comment by MIkeeJY** [comment]
You should use the enum Orientation in this not @Orientation in Recyclerview <3 @farzadnone

**Comment by yarolegovich** [comment]
Migrate to `1.4.0`, I resolved the naming ambiguity.
