### ISSUE TITLE
smoothScrollToPosition with InfiniteScrollAdapter

### ISSUE THREAD

**Issue by jintoga** [yarolegovich/DiscreteScrollView#68]
Hi, my app freezed when i tried to implement smoothScrollToPosition with InfiniteScrollAdapter and without it the app works normally. Any suggestions how can i fix this?

**Comment by 5mi13** [comment]
I have the same problem.

**Comment by yarolegovich** [comment]
I suppose you are calling it like:
```java
scrollView.smoothScrollToPosition(0);
```
Which causes the scroll view to layout ~(Integer.MAX_VALUE / 2) views. What you need to do is:
```java
int adapterPosition = adapter.getClosestPosition(0);
scrollView.smoothScrollToPosition(adapterPosition);
```
The [sample app](https://github.com/yarolegovich/DiscreteScrollView/tree/master/sample) contains a working example.

**Comment by Ehtihsham-Asghar** [comment]
I was facing the same issue but using 
`private var wrapper: InfiniteScrollAdapter<MyAdapter.ViewHolder>`
`carouselRecyclerView.smoothScrollToPosition(wrapper.getClosestPosition(position))` worked for me.

I am using `compile 'com.yarolegovich:discrete-scrollview:1.5.1'` library for infinite scroll.

**Comment by zhongxianyin** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
