### ISSUE TITLE
Infinite Circular Scroll

### ISSUE THREAD

**Issue by h777arsh** [yarolegovich/DiscreteScrollView#7]
Hi,
How can we support Infinite Circular in this view?

PS: Thanks for this awesome library.

**Comment by yarolegovich** [comment]
Hi, I am going to release this feature in a week or two.

**Comment by yarolegovich** [comment]
The problem with the feature is that a lot should be rewritten to handle a case when two views with the same adapter position are simultaneously visible on the screen. eg. we have 2, but 3 may be visible:
|[item1] [item0] [item1]|
I'm thinking about falling back to non-infinite scroll is such cases.

**Comment by sevar83** [comment]
I suppose the infinite scroll behavior can be emulated entirely on the
adapter level. On each currentPosition change just move the last item to
0-th position or vice versa depending on the direction of change.

**Comment by elveito** [comment]
Hi,

do you make any progress on this feature?

Thanks.

**Comment by yarolegovich** [comment]
Hi, @elveito. I've just returned from vacations and will try to finish the feature soon.
I already have a working adapter, but it currently doesn't support data set changes.

**Comment by elveito** [comment]
Hi, @yarolegovich - did you made any progress on this topic?

**Comment by anhlvph03609** [comment]
@yarolegovich i'm waiting for your good news

**Comment by yarolegovich** [comment]
Sorry guys, but I'm really short of free time. [Here](https://github.com/yarolegovich/DiscreteScrollView/#infinite-scroll) I described how to use the infinite scroll, but I really don't like the current implementation (especially data set changes handling). If you find any bugs in `1.2.0` please report them, I wasn't able to test it thoroughly.
