### ISSUE TITLE
problem with transformer

### ISSUE THREAD

**Issue by yiyibb** [yarolegovich/DiscreteScrollView#72]
I want to set the width and height dynamically, I can not use the scaleTransformer because the subviews in the item viewgroup will also scale-up/down.
this is my transformer but it dose not work。
` private float minWidth;
    private float maxMinDiffW;
    private float minHeight;
    private float maxMinDiffH;

    public ShopTransformer() {
        // test 
        minWidth = SystemUtil.dp2px(94);
        maxMinDiffW = SystemUtil.dp2px(140-94);
        minHeight = SystemUtil.dp2px(64);
        maxMinDiffH = SystemUtil.dp2px(64);
    }

    @Override
    public void transformItem(View item, float position) {
        Log.e("pos",""+position);
        float closenessToCenter = 1f - Math.abs(position);
        float width = minWidth + maxMinDiffW*closenessToCenter;
        float height = minHeight + maxMinDiffH*closenessToCenter;
        item.getLayoutParams().width = (int) width;
        item.getLayoutParams().height = (int) height;
        item.requestLayout();
    }`

**Comment by yarolegovich** [comment]
You can try scaling the container `View` up while scaling down its content.
