### ISSUE TITLE
Set Current Position

### ISSUE THREAD

**Issue by vorabhai** [yarolegovich/DiscreteScrollView#73]
Hello Sir, 
  How can i set current position set in "InfiniteScrollAdapter".  ? 

Because all time return first position or last position in adapter and every time start in first.
And I Add this line....
itemPicker.scrollToPosition(0);
Apps not work only black screen show in all time

**Comment by yarolegovich** [comment]
You need to use `adapter::getClosestPosition(int)`:
```java
int positionYouWantToScrollTo = 0;
int thisPositionInAdapter = adapter.getClosestPosition(positionYouWantToScrollTo);
scrollView.scrollToPosition(thisPositionInAdapter);
```

**Comment by vorabhai** [comment]
Its to let reply dear 
But No problem I will try to use this method..!
