### ISSUE TITLE
Image Not Loading

### ISSUE THREAD

**Issue by ravirajjak** [yarolegovich/DiscreteScrollView#74]
Hi,
OnBindViewHolder I Show Image Using Glide Library.
Once I start scrolling from Left to Right till the end at some position image doesnt display.
When I scroll from Right to Left the image is visible. I debugged but didnt find any cause everything executed properly.
Is it the library issue??

**Comment by yarolegovich** [comment]
I doubt it. [The sample](https://github.com/yarolegovich/DiscreteScrollView/tree/master/sample/src/main/java/com/yarolegovich/discretescrollview/sample) uses Glide for image loading and everything works fine.
