### ISSUE TITLE
make the DiscreteScrollView.canScrollHorizontally()  correct

### ISSUE THREAD

**Issue by wisonxu** [yarolegovich/DiscreteScrollView#77]
first, thanks for the great project! 
in my project, I want to support Horizontal Refresh for DiscreteScrollView,  but finally I was failed, the horizontal refresh library get the boundary value depends on View.canScrollHorizontally()。but DiscreteScrollLayoutManager does not override those methods, for make the  DiscreteScrollView.canScrollHorizontally()  correct, should override following methods in DiscreteScrollLayoutManager :

computeHorizontalScrollOffset()

computeHorizontalScrollRange()

computeHorizontalScrollExtent()

**Comment by wisonxu** [comment]
I've found another way to solve the problem,  just extends DiscreteScrollView and override canScrollHorizontally():

    @Override
    public boolean canScrollHorizontally(int direction) {
        LayoutManager layoutManager = getLayoutManager();
        if (layoutManager == null) return false;
        int count = layoutManager.getItemCount();
        int position = -1;
        try {
            Field field = layoutManager.getClass().getDeclaredField("currentPosition");
            field.setAccessible(true);
            position = (int) field.get(layoutManager);
        } catch (NoSuchFieldException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        }

        if (count == 0) {
            return false;
        } else {
            if (direction < 0) {
                return position != 0;
            } else {
                return position != count - 1;
            }
        }
    }

**Comment by yarolegovich** [comment]
Thanks, nice catch! Implemented this in `1.4.1`.
