### ISSUE TITLE
match_parent doesn't fill available space

### ISSUE THREAD

**Issue by bhylak** [yarolegovich/DiscreteScrollView#81]
First of all, this library is amazing! But, we have a fairly large problem.

We originally encountered #20, then tried setting the items to match_parent, but it does not actually match the parent size. Setting to an arbitrarily large size, however, did work.

**Comment by yarolegovich** [comment]
Would you mind posting here a layout which doesn't work?

**Comment by bhylak** [comment]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginTop="20dp"
        android:layout_marginBottom="20dp"
        android:id="@+id/item_questionlocation"
        android:orientation="vertical">
    <LinearLayout android:layout_width="match_parent"
                  android:layout_height="match_parent"
                  android:layout_gravity="center_vertical"
                  android:gravity="center_vertical"
                  android:orientation="vertical">
    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/tv_questionall_title"
        tools:text="What is your name?"
        android:textSize="48sp"
        android:paddingStart="56dp"
        android:textColor="#333333"/>

    <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="28dp"
            android:layout_marginEnd="36dp"
            android:layout_marginStart="56dp">
        <EditText
                android:layout_width="wrap_content"
                android:minWidth="300dp"
                android:layout_height="wrap_content"
                android:layout_centerVertical="true"
                android:layout_alignParentStart="true"
                android:id="@+id/entry_location_field"
                android:textSize="36sp"
                android:textColor="#333333"/>

        <Button
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentEnd="true"
                android:layout_centerInParent="true"
                android:id="@+id/btn_questionall_next"
                android:paddingStart="20dp"
                android:paddingEnd="20dp"
                android:paddingTop="4dp"
                android:paddingBottom="4dp"
                android:text="Next"
                android:textSize="36sp"
                android:background="#333333"
                android:textColor="#F7F7F7"/>
    </RelativeLayout>
    </LinearLayout>
</LinearLayout>

We have 4 different layouts all similar to this. But, the height is still determined by the smallest thing in the recycler view.

**Comment by yarolegovich** [comment]
I still have no idea what's wrong. Can you please post the layout where your DiscreteScrollView is defined?

**Comment by yarolegovich** [comment]
The view handles match_parent correctly, see #82.

**Comment by bhylak** [comment]
Interesting.. Displays properly in a recycler view though

**Comment by yarolegovich** [comment]
Can you also post the layout where DiscreteScrollView is defined please?
