### ISSUE TITLE
Card View

### ISSUE THREAD

**Issue by TasTugberk** [yarolegovich/DiscreteScrollView#82]
I would like to set the height of Card view with weight, but if I do it, it does not load the images. I would be happy, if you help me.
Thanks in advance.

**Comment by yarolegovich** [comment]
Show me your layout please.

**Comment by TasTugberk** [comment]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:gravity="center"
    android:weightSum="64">
    <android.support.v7.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="240dp"
        android:id="@+id/CardView"
        android:layout_height="0dp"
        android:layout_weight="36"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_gravity="center"
        android:background="#000000"
        app:cardCornerRadius="16dp">

        <com.makeramen.roundedimageview.RoundedImageView
            android:background="#ffffff"
            android:id="@+id/image"
            android:scaleType="fitXY"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:riv_corner_radius="16dp"/>
    </android.support.v7.widget.CardView>
</LinearLayout>

**Comment by TasTugberk** [comment]
I upload screenshot of layout to the following link.

[https://ibb.co/dKkuFc](url)

**Comment by yarolegovich** [comment]
The link doesn't work. Post it as text please.

**Comment by TasTugberk** [comment]
https://ibb.co/dKkuFc

**Comment by TasTugberk** [comment]
When I run the application nothing is loaded, but if I set height with some number then it works well.

**Comment by yarolegovich** [comment]
I don't understand what does "nothing is loaded" mean. Does a LinearLayout have a zero height? If you use the same adapter with RecyclerView and LinearLayoutManager, will it work?

**Comment by TasTugberk** [comment]
I mean none of the photos are loaded. No as you see in the screenshot it match_parent. I use the following 
adapter:

` 

    public class ShopAdapter extends RecyclerView.Adapter<ShopAdapter.ViewHolder> {

        private List<Movies> data;
        Context context;

        public ShopAdapter(List<Movies> data,Context context) {
            this.data = data;
            this.context = context;
        }

        @Override
        public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
            LayoutInflater inflater = LayoutInflater.from(parent.getContext());
            View v = inflater.inflate(R.layout.item_shop_card, parent, false);
            return new ViewHolder(v);
        }

        @Override
        public void onBindViewHolder(ViewHolder holder, int position) {
            Glide.with(context)
                    .load(data.get(position).getImage())
                    .into(holder.image);
        }

        @Override
        public int getItemCount() {
            return data.size();
        }

        class ViewHolder extends RecyclerView.ViewHolder {

            private RoundedImageView image;

            public ViewHolder(View itemView) {
                super(itemView);
                image = (RoundedImageView) itemView.findViewById(R.id.image);
            }
        }
    }

`

**Comment by yarolegovich** [comment]
And how do you define you DiscreteScrollView?

**Comment by TasTugberk** [comment]
`




    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="center"
        android:background="#ffffff"
        android:weightSum="64"
        android:orientation="vertical">

        <com.yarolegovich.discretescrollview.DiscreteScrollView
            android:id="@+id/item_picker"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="36" />
    </LinearLayout>

</android.support.constraint.ConstraintLayout>



`

**Comment by yarolegovich** [comment]
I've just tried your item layout in a sample project and everything worked correctly on lib version `1.4.4`. 
I'm pretty sure that issue is not related to the library. 

> If you use the same adapter with RecyclerView and LinearLayoutManager, will it work?

Replace your DiscreteScrollView with a RecyclerView and check if images are visible or not. If not, then the problem is in your layout.

**Comment by TasTugberk** [comment]
Can you share your adapter with me ? 
Let me try it, I will inform you.

**Comment by yarolegovich** [comment]
[Here it is](https://github.com/yarolegovich/DiscreteScrollView/blob/master/sample/src/main/java/com/yarolegovich/discretescrollview/sample/shop/ShopAdapter.java), but I can assure you that the problem is not in the adapter. I bet it is in your activity/fragment layout.

**Comment by TasTugberk** [comment]
You are right, it change it to RecyclerView images are not visible. I have just two layout, I shared both of them with you. What could be the problem I could not solve it :(

**Comment by yarolegovich** [comment]
I don't see the top of your layout with DiscreteScrollView, but if <android.support.constraint.ConstraintLayout> is the root element, it is just useless and can be safely removed. Also this will probably fix your problem.

**Comment by TasTugberk** [comment]
You are right, I changed it to LinearLayout and it works, but now I loose the previous and the next image which are normally located at the left and the right of screen.

https://imgur.com/5hsAw6N

**Comment by yarolegovich** [comment]
Because your width is match_parent. I'm not responding here anymore.
