### ISSUE TITLE
Accessing Dataset in onCurrentItemChanged

### ISSUE THREAD

**Issue by m-rahimy** [yarolegovich/DiscreteScrollView#86]
I want to access the data model of the currently showing carousel item.
I could not find this in the docs. tried to log the two arguments to see if they look like an index, but they are not indices.

```
recyclerview?.addOnItemChangedListener { viewHolder, adapterPosition ->
            Log.d(TAG, "item changed viewHolder " + viewHolder)
            Log.d(TAG, "item changed viewHolder adapterPosition " + viewHolder?.adapterPosition)
            Log.d(TAG, "item changed viewHolder position  " + viewHolder?.position)
            Log.d(TAG, "item changed adapterPosition " + adapterPosition)
```

Do I have to get the index by calling a method from the library? checking SO didn't lead to any usable solution. I think there is no way to access the currently showing item.

**Comment by yarolegovich** [comment]
`adapterPosition` is what you're looking for. Do you use `InfiniteScrollAdapter`?

**Comment by yarolegovich** [comment]
Anyway, just put some effort and check how this was done in the [sample app](https://github.com/yarolegovich/DiscreteScrollView/tree/master/sample/src/main/java/com/yarolegovich/discretescrollview/sample).

**Comment by m-rahimy** [comment]
yes. with `InfiniteScrollAdapter` , `adaperPosition` is an integer much bigger than the actual length of my dataset array. Do I need to perform the modulo arithmetic? This gives me the wrong index:

`adapterPosition % provinceAdapter!!.itemCount`

**Comment by yarolegovich** [comment]
Have you tried to [read the docs](https://github.com/yarolegovich/DiscreteScrollView#infinite-scroll) or to look at [the sample code](https://github.com/yarolegovich/DiscreteScrollView/blob/master/sample/src/main/java/com/yarolegovich/discretescrollview/sample/shop/ShopActivity.java#L112)?

**Comment by m-rahimy** [comment]
Those are descriptive method names, Thanks to mention; so I know that what method I should be using.  The problem is that sometimes `cityInfiniteScrollAdapter!!.getRealPosition(adapterPosition)` gives me the wrong index. I think the method skips the last item in dataset.

**Comment by yarolegovich** [comment]
I doubt it. The sample works fine and no one has ever reported this issue.
