### ISSUE TITLE
How to get actual data onScrollEnd

### ISSUE THREAD

**Issue by pinkeshdarji** [yarolegovich/DiscreteScrollView#87]
I can get the adapterPosition onScrollEnd. But How do I make use of it or how do I get actual value binded at that position in card. For example, In card at position 0 There is name in textview. So when that card is visible I want to get that name and disaply it in another layout outside of DiscreteScrollView. 
Can anyone please help me ?

**Comment by yarolegovich** [comment]
You can find different usage examples in the [sample app](https://github.com/yarolegovich/DiscreteScrollView/tree/master/sample/src/main/java/com/yarolegovich/discretescrollview/sample).

**Comment by pinkeshdarji** [comment]
I found out in the sample.
    @Override
    public void onCurrentItemChanged(@Nullable RecyclerView.ViewHolder viewHolder, int position) {
        int positionInDataSet = infiniteAdapter.getRealPosition(position);
        onItemChanged(data.get(positionInDataSet));
    }

Thanks @yarolegovich
