### ISSUE TITLE
InfiniteScrollAdapter not working correctly after add item to Adapter

### ISSUE THREAD

**Issue by vilimas** [yarolegovich/DiscreteScrollView#88]
I have problems with InfiniteScrollAdapter after I add an item to my adapter. DiscreteScrollView always shows only last item.
First I initialize my DiscreteScrollView like this
`pingAdapterWraper = InfiniteScrollAdapter.wrap(pingAdapter) `
`v.pingPager.adapter = pingAdapterWraper`
In async process I add items to my adapter. I call `notifyDataSetChanged()` in my adapter and in InfiniteScrollAdapter, but what not fix problem

**Comment by yarolegovich** [comment]
What does "shows only last item" mean?

**Comment by vilimas** [comment]
I have the list of 40 items and when scrolling all my cards have last item information.
For example:
Adapter item list after I added all items:
Name1
Name2
Name3

DiscreteScrollView shows:
Name3 -> Name3 -> Name3

What I want:
Name1 -> Name2 -> Name3

**Comment by yarolegovich** [comment]
Does everything work fine when you're not using InfiniteScrollAdapter?

**Comment by vilimas** [comment]
Without InfiniteScrollAdapter it's working fine

**Comment by yarolegovich** [comment]
It will be helpful, if you paste part of the code which modifies data set and notifies changes.

**Comment by vilimas** [comment]
Code in my adapter to add new item
```    
fun addItem(ping :RLPing){
        pingList.add(ping)
        notifyDataSetChanged()
    }
```
In my main class: 
```
 data.forEach { item ->
         pingAdapter.addItem(item)
         ...
}
pingAdapterWraper.notifyDataSetChanged()
```
Strange behavior if I open DiscreteScrollView view and put app in background and then bring back. Items display correctly.

I believe it can be bug in `InfiniteScrollAdapter` `mapPositionToReal(int position)` or `resetRange(int newPosition)`

**Comment by yarolegovich** [comment]
I'll definitely look into it this Saturday.

**Comment by yarolegovich** [comment]
I can't reproduce the behavior you describe. I will appreciate if someone creates a project where the issue can be observed.

**Comment by sikrinick** [comment]
The reason is pretty simple, it lies in a class `DataSetChangeDelegate` of `InfiniteScrollAdapter`.
On any `notifyData*`, it calls for `onChanged()`, in which `resetRange(0)`, while in `void resetRange(int newPosition)` it just does next:
```
currentRangeStart = Integer.MAX_VALUE / 2;
            layoutManager.scrollToPosition(currentRangeStart + newPosition);
```
This means, that it just scrolls to `Integer.MAX_VALUE / 2` position, that represents a starting position.

**Comment by yarolegovich** [comment]
@sikrinick well, the code you're talking about just makes an item at position 0 to be the current item after any of the notify* methods is called, and I'm aware of this. What vilimas describes is a completely different behavior and a bug, which I'm unfortunately unable to reproduce.

**Comment by sikrinick** [comment]
@yarolegovich I suspect there is certain connection. I've observed similar behaviour noticed by opening post.
If I am adding new items to a list, it is scrolling to position `Integer.MAX / 2`, even if if previous position was `(Integer.MAX / 2) + 5`. 
That may make one to add `scrollToPosition(5)`, where 5 is position before adding new items, even though it is incorrect, and should be `(getCurrentPosition() + 5)`, as for now after `notifyData*` starting position would be always `Integer.MAX / 2` for adapter and 0  for item list. `scrollToPosition(5)` will actually make it look like as a list of last added items, as it is how it looks like on that position of an adapter.

**Comment by vilimas** [comment]
I finally found some time for siting down to my problem and find solution. I was using 
```pager.scrollToPosition(index)```
instead
```pager.scrollToPosition(pingAdapterWraper.getClosestPosition(index))```

**Comment by yarolegovich** [comment]
> I finally found some time for siting down to my problem and find solution.

I'm glad to hear that.
