### ISSUE TITLE
Can add support EmptyRecyclerView ?

### ISSUE THREAD

**Issue by CMingTseng** [yarolegovich/DiscreteScrollView#89]
Dear Sir

how to set EmptyView ?

https://gist.github.com/adelnizamutdinov/31c8f054d1af4588dc5c

THX

**Comment by yarolegovich** [comment]
Nothing prevents you from subclassing DiscreteScrollView as done with RecyclerView in the gist, even though I think it's better to let an adapter handle empty view visibility.
