### ISSUE TITLE
ViewHolder cannot show correct width

### ISSUE THREAD

**Issue by kaiyan910** [yarolegovich/DiscreteScrollView#9]
![1111](https://cloud.githubusercontent.com/assets/9815472/24149873/f6728ba4-0e7e-11e7-8a45-205c7e775fb4.png)

I am trying to implement a Google play store like screenshot scroll view with different image width.
As you can see from the image above the last image can not show the full width (the black border is the background of the viewholder), I have tried to set the LayoutParams in runtime but still nothing change

```
 mViewImage.setLayoutParams(new RelativeLayout.LayoutParams(bitmap.getWidth(), bitmap.getHeight()));
 mViewImage.setImageBitmap(bitmap);
```

and the holder xml like this

```
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:id="@+id/wrapper"
    android:background="@android:color/black"
    android:padding="4dp">

    <ImageView
        android:id="@+id/image"
        android:layout_centerInParent="true"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" />

</RelativeLayout>
```

is there any hints to solve this problem ?

**Comment by yarolegovich** [comment]
How is this related to the library? 
You set width and height of an ImageView to the width and height of a bitmap, so this is a problem of your bitmap dimensions. 
So the hint will be to practice xml layout skills, library doesn't affect ViewHolders and layouts, it only determines positions of views and scroll logic.
