### ISSUE TITLE
Swipe Listview in  Discrete Scroll View

### ISSUE THREAD

**Issue by TasTugberk** [yarolegovich/DiscreteScrollView#90]
Hi, thanks for such a useful library. 
I have a swipe listview within the item of discrete scroll view, but when I try to swipe on a listview element, discrete view scrolls itself. Is it possible to disable scrolling in some part/parts of discrete scroll view item.
Thanks in advance.

**Comment by yarolegovich** [comment]
It's hard to answer your question. The library doesn't do anything special with touches, so if you can make this work with a standard RecyclerView, the same should do for DiscreteScrollView.
