### ISSUE TITLE
getRealPosition Issues with infiniteAdapter

### ISSUE THREAD

**Issue by jaymin2609** [yarolegovich/DiscreteScrollView#91]
While getting real position from selected position it gives wrong value for second last position.And its happen while scrolling from right to left it works fine with opposite scrolling.

Here is my code : 

 @Override
    public void onCurrentItemChanged(@Nullable AdapterBottomSlider.MyViewHolder viewHolder, int adapterPosition) {
        if (viewHolder != null) {
            LogUtils.LOGD(TAG, "pos : " + String.valueOf(adapterPosition));
            int pos = infiniteAdapter.getRealPosition(adapterPosition);
            LogUtils.LOGD(TAG, "pos : " + String.valueOf(pos));
                    
           
            viewHolder.makeBigger();
        }
    }

**Comment by yarolegovich** [comment]
Provide please some code which I can run to see the issue, everything works fine in the sample app.

**Comment by divysoni3** [comment]
@yarolegovich I have produced the problem in your sample app, go to your layout `item_shop_card` set width height of cardView 100dp and margin 0dp.

```
<android.support.v7.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="100dp"
    android:layout_height="100dp"
    android:layout_margin="0dp"
    android:layout_gravity="center">

    <ImageView
        android:id="@+id/image"
        android:scaleType="centerCrop"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</android.support.v7.widget.CardView>
```

Now you can see the same problem.
Please give the solution for this.

**Comment by yarolegovich** [comment]
Hopefully the same as #125
