### ISSUE TITLE
Do not scroll the UI

### ISSUE THREAD

**Issue by TasTugberk** [yarolegovich/DiscreteScrollView#93]
Hi, I try to scroll discrete scroll view according to number coming from intent, I have the following code;

https://ibb.co/b17boS 

As you see in the log, position is changing, but user interface is never scrolling to new position in this case it's 2(two). What can be wrong ?

**Comment by yarolegovich** [comment]
Use `scrollToPosition(infiniteScrollAdapter.getClosestPosition(2))`

**Comment by TasTugberk** [comment]
Are you sure; I changed code to;

`infiniteAdapter = InfiniteScrollAdapter.wrap(new ToDoAdapter(titles,getActivity()));
        discreteScrollView.setAdapter(infiniteAdapter);
        discreteScrollView.setSlideOnFling(true);
        discreteScrollView.setSlideOnFlingThreshold(2000);
        discreteScrollView.setItemTransformer(new ScaleTransformer.Builder().setMinScale(.91f).build());
        Log.i("Position",String.valueOf(discreteScrollView.getCurrentItem()));
        discreteScrollView.scrollToPosition(infiniteAdapter.getClosestPosition(2));
        Log.i("Position",String.valueOf(discreteScrollView.getCurrentItem()));`

but nothing is changed it's not scrolling.

**Comment by yarolegovich** [comment]
If I this doesn't work, the problem is somewhere else in the code.

**Comment by TasTugberk** [comment]
Ok, but other things works well, let me check again.

**Comment by TasTugberk** [comment]
Everything look fine, what could be the problem, please help me.

**Comment by yarolegovich** [comment]
I can't help you without knowing how to reproduce the issue. Scrolling works fine in test cases and the sample. My advice is to look at the sample provided with this library and debug your code.

**Comment by TasTugberk** [comment]
Ok, thank you for helping me.

**Comment by TasTugberk** [comment]
Excuse me sir, one more question as I see `scrollToPosition(infiniteAdapter.getClosestPosition(2))` does not call scroll listener, is there any way to do that ?
