### ISSUE TITLE
DiscreteScrollLayoutManager can public ?

### ISSUE THREAD

**Issue by CMingTseng** [yarolegovich/DiscreteScrollView#98]
Dear Sir

because i want add  RecyclerView Indicator 

https://stackoverflow.com/questions/33841363/how-to-make-a-page-indicator-for-horizontal-recyclerview 

https://github.com/kingfisherphuoc/EasyRecyclerViewIndicator

so i need get LayoutManager to know  now position

so can let DiscreteScrollLayoutManager public ?

THX

**Comment by bernaferrari** [comment]
Up. I want to implement RecyclerView prefetching from Glide, need it to be public.

**Comment by yarolegovich** [comment]
As far as I can see, in the example you provided `LayoutManager` is used only to make a call to `findFirstVisibleItemPosition();` which can be substituted with `scrollView.getCurrentItem();` when using DiscreteScrollView.

**Comment by phearme** [comment]
@yarolegovich we also need to call `findViewByPosition()` from the `LayoutManager`. is there an alternative to get a view by position in DiscreteScrollView?

**Comment by myJarvis** [comment]
> @yarolegovich we also need to call `findViewByPosition()` from the `LayoutManager`. is there an alternative to get a view by position in DiscreteScrollView?
> 
> **EDIT**: I'm using this (if anyone is interested)
> `discreteScrollView.getViewHolder(discreteScrollView.getCurrentItem()).itemView`
> 
> **EDIT2**: decided to make my own anyways
> https://github.com/phearme/DiscreteScrollViewIndicator

It doesnt work with InfiniteScrollAdapter @r-cohen r-cohen
